### PR TITLE
Enhanced GitHub Actions Workflow for DingusPPC Build Automation

### PR DESCRIPTION
**Pull request by sdkmap**
This GitHub Actions workflow automates the build process for DingusPPC, generating binaries for both Windows and Linux platforms. Upon completion, the script seamlessly uploads the compiled binaries to artifacts, simplifying distribution.

The script currently supports five build modes:

**Normal Linux Builds**: This mode compiles the Linux binaries and uploads them to artifacts.

**MSYS2**: Included for testing purposes, this mode always shows as successful and is intended for potential future use in fixing MSYS2 builds.

**vsbuild Clang**: Compiles the project using the Clang compiler in Visual Studio 2022 and uploads the resulting binaries.

**vsbuild MSVC**: Similar to the above mode but uses the MSVC compiler, useful for debugging purposes.

**vsbuild MSVC MSBuild**: Another test mode to check successful compilation using MSBuild and SLN.

Let me know if you need further adjustments or assistance!

### CODE REVIEW

**Comment by dingusdev** [comment]
Looks good. The only recommendation is see if you can squash them.

**Comment by sdkmap** [comment]
> Looks good. The only recommendation is see if you can squash them.

By squashing them, you mean compressing all of the binaries into a single file?

**Comment by MaddTheSane** [comment]
The commits into one.

**Comment by sdkmap** [comment]
> The commits into one.

Ok, I get it. I will see what I can do about it.

**Pull request closed without merging**
